clear all; close all; clc;
% These are for 100% scans, tx_power=-8dBm
fileID = fopen('adv_interval\always_scan_100msadv.log');
data = fscanf(fileID,'%d %d', [2 Inf]);
data = data';
offset = data(1,1);
data(:,1) = data(:,1) - offset;
data(:,1) = data(:,1)/1000;
figure(1);
plot(data(:,1),data(:,2));
fclose(fileID);
hold on;
xlabel('Time (s)');
ylabel('RSSI');
title('Adv interval=100ms');

fileID = fopen('adv_interval\always_scan_250msadv.log');
data = fscanf(fileID,'%d %d', [2 Inf]);
data = data';
offset = data(1,1);
data(:,1) = data(:,1) - offset;
data(:,1) = data(:,1)/1000;
figure(2);
plot(data(:,1),data(:,2));
fclose(fileID);
hold on;
xlabel('Time (s)');
ylabel('RSSI');
title('Adv interval=250ms');

fileID = fopen('adv_interval\always_scan_500msadv.log');
data = fscanf(fileID,'%d %d', [2 Inf]);
data = data';
offset = data(1,1);
data(:,1) = data(:,1) - offset;
data(:,1) = data(:,1)/1000;
figure(3);
plot(data(:,1),data(:,2));
fclose(fileID);
hold on;
xlabel('Time (s)');
ylabel('RSSI');
title('Adv interval=500ms');

fileID = fopen('adv_interval\always_scan_750msadv.log');
data = fscanf(fileID,'%d %d', [2 Inf]);
data = data';
offset = data(1,1);
data(:,1) = data(:,1) - offset;
data(:,1) = data(:,1)/1000;
figure(4);
plot(data(:,1),data(:,2));
fclose(fileID);
hold on;
xlabel('Time (s)');
ylabel('RSSI');
title('Adv interval=750ms');

fileID = fopen('adv_interval\always_scan_1000msadv.log');
data = fscanf(fileID,'%d %d', [2 Inf]);
data = data';
offset = data(1,1);
data(:,1) = data(:,1) - offset;
data(:,1) = data(:,1)/1000;
figure(5);
plot(data(:,1),data(:,2));
fclose(fileID);
hold on;
xlabel('Time (s)');
ylabel('RSSI');
title('Adv interval=1000ms');